; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "caret text editor(demo)"
#define MyAppVersion "0.3"
#define MyAppPublisher "save-as"
#define MyAppURL "https://github.com/mikon1992/caret.git"
#define MyAppExeName "text_editor.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".txt"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5B38D0D8-CE80-457C-9D98-DA03A2EE85B2}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Users\rafia\Downloads\license.txt
InfoBeforeFile=C:\Users\rafia\Downloads\info.txt
InfoAfterFile=C:\Users\rafia\Downloads\Credit.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\rafia\OneDrive\Documents\GitHub\caret\output
OutputBaseFilename=mysetup
SetupIconFile=C:\Users\rafia\Downloads\nycto.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\edit.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\GUI_code.glade"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libasprintf-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libatk-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libatomic-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libb2-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libbrotlicommon.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libbrotlidec.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libbrotlienc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libbz2-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libcairo-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libcairo-gobject-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libcairo-script-interpreter-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libcares-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libcharset-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libcrypto-3-x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libcurl-4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libdatrie-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libdeflate.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libepoxy-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libexpat-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libffi-8.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libfontconfig-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libformw6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libfreetype-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libfribidi-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgailutil-3-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgdk_pixbuf-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgdk-3-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgif-7.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgio-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgirepository-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgladeui-2-13.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libglib-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgmodule-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgmp-10.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgmpxx-4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgnutls-30.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgnutls-openssl-27.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgnutlsxx-30.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgobject-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgomp-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgraphene-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgraphite2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstadaptivedemux-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstallocators-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstanalytics-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstapp-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstaudio-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstbadaudio-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstbase-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstbasecamerabinsrc-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstcheck-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstcodecparsers-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstcodecs-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstcontroller-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstcuda-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstd3d11-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstd3d12-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstd3dshader-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstdxva-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstfft-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstgl-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgsthip-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstinsertbin-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstisoff-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstmpegts-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstmse-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstnet-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstpbutils-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstphotography-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstplay-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstplayer-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstreamer-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstriff-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstrtp-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstrtsp-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstsctp-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstsdp-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgsttag-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgsttranscoder-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgsturidownloader-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstva-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstvideo-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstvulkan-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstwebrtc-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgstwebrtcnice-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgthread-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgtk-3-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libgtk-4-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libharfbuzz-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libharfbuzz-gobject-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libharfbuzz-raster-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libharfbuzz-subset-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libharfbuzz-vector-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libhistory8.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libhogweed-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libiconv-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libidn2-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libintl-8.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libisl-23.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libjbig-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libjpeg-8.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libjson-glib-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libLerc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\liblzma-5.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\liblzo2-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libmenuw6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libmpc-3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libmpdec++-4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libmpdec-4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libmpfr-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libncurses++w6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libncursesw6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libnettle-8.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libnghttp2-14.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libnghttp3-9.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libngtcp2_crypto_gnutls-8.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libngtcp2_crypto_ossl-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libngtcp2-16.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libnice-10.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libogg-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libopus-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\liborc-0.4-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\liborc-test-0.4-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libp11-kit-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpanelw6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpango-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpangocairo-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpangoft2-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpangowin32-1.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpcre2-16-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpcre2-32-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpcre2-8-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpcre2-posix-3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpixman-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpng16-16.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libproxy-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpsl-5.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpxbackend-1.0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpython3.14.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libpython3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libquadmath-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libreadline8.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\librsvg-2-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libsharpyuv-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libsqlite3-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libssh2-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libssl-3-x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libsystre-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libtasn1-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libtermcap-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libthai-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libtheora-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libtheoradec-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libtheoraenc-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libtiff-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libtiffxx-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libtre-5.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libturbojpeg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libunistring-5.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libva.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libva_win32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libvorbis-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libvorbisenc-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libvorbisfile-3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libwebp-7.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libwebpdecoder-3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libwebpdemux-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libwebpmux-3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libxml2-16.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\libzstd.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\nycto.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\style.css"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\tcl86.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\tk86.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\vulkan-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\rafia\OneDrive\Documents\GitHub\caret\libs\zlib1.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

